[package]
name = "monkey_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.46", features = ["derive"] }
fnv = "1.0.7"                                        # for hashing
# lazy_static = "1.5.0"
